### ISSUE TITLE
Используй Kotlin `const` для небольшой оптимизации 

### ISSUE THREAD

**Issue by JohnMars** [azamat-kln/todoApp#1]
https://kotlinlang.org/docs/reference/properties.html#compile-time-constants

https://github.com/azamat-kln/todoApp/blob/41c4bb2c3cdff42578dcb03212193f2b0304d188/app/src/main/java/com/example/roomcoroutines/ui/main/MainActivity.kt#L29

**Comment by azamat-kln** [comment]
Yeap
